# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# TODO(b/406139789):
# According to MTK, MCDI takes 40 seconds to initialize on boot (on Rauru).
# If suspend is triggered before MCDI is ready, SPM doesn't receive signals from
# MCDI and trigger AP_IN_SLEEP_L to notify EC, and AP is considered hard-hang
# from EC perspective which causes EC to force reboot the system.
#
# Register a temporary wake lock on boot to prevent early suspend to accommodate
# MCDI init delay until we figure out a better solution. The wake lock will be
# automatically unregistered after a 40-second timeout after boot.

description     "Prevent early suspend on boot for MCDI init delay"
author          "fshao@chromium.org"

# No need to be killed.
oom score never

start on stopped pre-startup
task

script
  # 40-second in nanoseconds
  echo "mtk_mcdi 40000000000" > /sys/power/wake_lock
end script
