SectionVerb {
	Value {
		FullySpecifiedUCM "1"
	}
	EnableSequence [
		cdev "hw:sofmt8196tas256"
		cset "name='DAC1 MIXL DAC1 Switch' 1"
		cset "name='DAC1 MIXR DAC1 Switch' 1"
		cset "name='DAC1 Playback Volume' 118"
		cset "name='Stereo1 DAC MIXL DAC L1 Switch' 1"
		cset "name='Stereo1 DAC MIXR DAC R1 Switch' 1"
		cset "name='DAC L1 Source' 'Stereo1 DAC Mixer'"
		cset "name='DAC R1 Source' 'Stereo1 DAC Mixer'"
		cset "name='STO1 ADC Capture Switch' off"
		cset "name='STO1 ADC Capture Volume' 24"
		cset "name='RECMIX1L CBJ Switch' 1"
		cset "name='Stereo1 ADC L Mux' 0"
		cset "name='IF1 01 ADC Swap Mux' 2"
		cset "name='CBJ Boost Volume' 28"
		cset "name='Stereo1 ADC L1 Mux' 1"
		cset "name='Stereo1 ADC R1 Mux' 1"
		cset "name='Stereo1 ADC MIXL ADC2 Switch' 0"
		cset "name='Stereo1 ADC MIXR ADC2 Switch' 0"
		cset "name='Stereo1 ADC MIXL ADC1 Switch' 1"
		cset "name='Stereo1 ADC MIXR ADC1 Switch' 1"
		cset "name='HDMI_CH0_MUX' CH0"
		cset "name='HDMI_CH1_MUX' CH1"
		cset "name='HDMI_CH2_MUX' CH2"
		cset "name='HDMI_CH3_MUX' CH3"
		cset "name='HDMI_CH4_MUX' CH4"
		cset "name='HDMI_CH5_MUX' CH5"
		cset "name='HDMI_CH6_MUX' CH6"
		cset "name='HDMI_CH7_MUX' CH7"
		cset-tlv "name='CODEC_ADAPTER1.0 Waves Speakers Setup 1' /opt/waves/navi.rt5682/waves_params_speaker.bin"
		cset-tlv "name='CODEC_ADAPTER2.0 Waves Headphones Setup 2' /opt/waves/navi.rt5682/waves_params_headphone.bin"
	]
	DisableSequence [
		cdev "hw:sofmt8196tas256"
	]
}

SectionDevice."Speaker".0 {
	Value {
		PlaybackPCM "hw:sofmt8196tas256,0"
	}
	EnableSequence [
		cdev "hw:sofmt8196tas256"
		cset "name='I2SOUT4_CH1 DL_24CH_CH1' 1"
		cset "name='I2SOUT4_CH2 DL_24CH_CH2' 1"
		cset "name='I2SOUT4_CH3 DL_24CH_CH3' 1"
		cset "name='I2SOUT4_CH4 DL_24CH_CH4' 1"
	]
	DisableSequence [
		cdev "hw:sofmt8196tas256"
		cset "name='I2SOUT4_CH1 DL_24CH_CH1' 0"
		cset "name='I2SOUT4_CH2 DL_24CH_CH2' 0"
		cset "name='I2SOUT4_CH3 DL_24CH_CH3' 0"
		cset "name='I2SOUT4_CH4 DL_24CH_CH4' 0"
	]
}

SectionDevice."Headphone".0 {
	Value {
		PlaybackPCM "hw:sofmt8196tas256,1"
		JackDev "sof-mt8196_tas2563_5682 Headset Jack"
		JackSwitch "2"
	}
	EnableSequence [
		cdev "hw:sofmt8196tas256"
		cset "name='I2SOUT6_CH1 DL1_CH1' 1"
		cset "name='I2SOUT6_CH2 DL1_CH2' 1"
	]
	DisableSequence [
		cdev "hw:sofmt8196tas256"
		cset "name='I2SOUT6_CH1 DL1_CH1' 0"
		cset "name='I2SOUT6_CH2 DL1_CH2' 0"
	]
}

SectionDevice."Internal Mic".0 {
	Value {
		CapturePCM "hw:sofmt8196tas256,2"
		CaptureChannelMap "0 1 -1 -1 -1 -1 -1 -1 -1 -1 -1"
		IntrinsicSensitivity "-2600"
	}
	EnableSequence [
		cdev "hw:sofmt8196tas256"
		cset "name='ADDA_UL_Mux' AP_DMIC"
		cset "name='UL0_CH1 ADDA_UL_CH1' 1"
		cset "name='UL0_CH2 ADDA_UL_CH2' 1"
	]
	DisableSequence [
		cdev "hw:sofmt8196tas256"
		cset "name='UL0_CH1 ADDA_UL_CH1' 0"
		cset "name='UL0_CH2 ADDA_UL_CH2' 0"
	]
}

SectionDevice."Mic".0 {
	Value {
		CapturePCM "hw:sofmt8196tas256,3"
		JackDev "sof-mt8196_tas2563_5682 Headset Jack"
		JackSwitch "4"
		CaptureChannelMap "0 1 -1 -1 -1 -1 -1 -1 -1 -1 -1"
	}
	EnableSequence [
		cdev "hw:sofmt8196tas256"
		cset "name='UL1_CH1 I2SIN6_CH1' 1"
		cset "name='UL1_CH2 I2SIN6_CH2' 1"
	]
	DisableSequence [
		cdev "hw:sofmt8196tas256"
		cset "name='UL1_CH1 I2SIN6_CH1' 0"
		cset "name='UL1_CH2 I2SIN6_CH2' 0"
	]
}

SectionDevice."HDMI".0 {
	Value {
		PlaybackPCM "hw:sofmt8196tas256,5"
		JackDev "sof-mt8196_tas2563_5682 DP Jack"
	}
	EnableSequence [
		cdev "hw:sofmt8196tas256"
		cset "name='DPTX_OUT_MUX' 1"
		cset "name='DPTX_VIRTUAL_OUT_MUX' 1"
	]
	DisableSequence [
		cdev "hw:sofmt8196tas256"
		cset "name='DPTX_OUT_MUX' 0"
		cset "name='DPTX_VIRTUAL_OUT_MUX' 0"
	]
}

SectionDevice."HDMI1".0 {
	Value {
		PlaybackPCM "hw:sofmt8196tas256,6"
		JackDev "sof-mt8196_tas2563_5682 HDMI Jack"
	}
	EnableSequence [
		cdev "hw:sofmt8196tas256"
		cset "name='I2SOUT3_CH1 DL2_CH1' 1"
		cset "name='I2SOUT3_CH2 DL2_CH2' 1"
	]
	DisableSequence [
		cdev "hw:sofmt8196tas256"
		cset "name='I2SOUT3_CH1 DL2_CH1' 0"
		cset "name='I2SOUT3_CH2 DL2_CH2' 0"
	]
}
