# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# For background see:
# https://crbug.com/939979
# https://issuetracker.google.com/136040671

description "Initialize Panel Self-Refresh (PSR) settings"
author "chromium-os-dev@chromium.org"

start on starting boot-splash
task

script
  set -e

  psr_enable_path=/sys/module/i915/parameters/enable_psr
  procver="$(dmidecode -s processor-version)"

  # CPU model is used as a proxy for display resolution, because the latter is
  # not available from the Direct Rendering Manager (DRM) Linux subsystem this
  # early in the boot process.
  case "${procver%%-*}" in
    "Intel(R) Core(TM) m3" | "Intel(R) Core(TM) i5")
      echo 0 > "${psr_enable_path}"
      ;;
    "Intel(R) Core(TM) i7")
      echo 1 > "${psr_enable_path}"
      ;;
    *)
      false
  esac
end script
