#!/bin/bash

# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

readonly GPIO=345
readonly GPIO_PATH="/sys/class/gpio/gpio${GPIO}/"

log() {
  logger "[modem]" "$@"
}

has_modem() {
  cros_config /modem firmware-variant > /dev/null
}

has_modem || exit 0

log "stop modemmanager"
stop modemmanager

if [[ ! -d ${GPIO_PATH} ]]; then
  log "export GPIO ${GPIO}"
  echo ${GPIO} > /sys/class/gpio/export
  echo out > "${GPIO_PATH}/direction"
fi

log "assert GPIO ${GPIO}"
echo 0 > "${GPIO_PATH}/value"
