#!/bin/bash

# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

readonly GPIO=345
readonly GPIO_PATH="/sys/class/gpio/gpio${GPIO}/"

log() {
  logger "[modem]" "$@"
}

has_modem() {
  cros_config /modem firmware-variant > /dev/null
}

has_modem || exit 0

if [[ -d ${GPIO_PATH} ]]; then
  log "de-assert GPIO ${GPIO}"
  echo 1 > "${GPIO_PATH}/value"
fi
