# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

description "Preload Qualcomm's remote processor driver"
author "chromium-os-dev@chromium.org"

# This needs to execute when the boot-service starts and can
# run in parallel to the boot-service.
start on starting boot-services

# There is a similar .conf file /init/upstart/preload-network.conf
# which find the network interfaces and loads them in the following
# boots. In case of trogdor, we cannot use that config because
# trogdor has a dependency on remote processor driver and the preload
# network.conf doesn't address that, neither can we easily modify it
# because its used in multiple projects. I have created a ticket
# to research a long term generic solution for that, http://b/166836900.
# Trogdor uses combo chip which contains LTE, Wifi, BT.
# The wifi is sub module that gets initialized the modem processor
# which is a remote processor. The firmware on the modem processor
# is loaded by the remote processor driver(qcom-q6v5-mss). The remote
# processor driver should be loaded early into the boot so the modem
# processor can boot early.
exec modprobe qcom_q6v5_mss
