# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Configure Bluetooth controller to power down during suspend
# Oak and Hana (which use MVL8897 and MVL8997) encounter a high rate of suspend
# failures due to -EBUSY from the Marvell BT driver (b/168152910). For better
# suspend stability, we just power down the controller on suspend and power up
# on resume.
# This is acceptable on Chromebooks (which can be woken up with on-board
# keyboard or touch pad) but not on Chromeboxes. Hence why this quirk is applied
# only to Oak/Hana and not all users of this Marvell controller.
options btmrvl_sdio power_down_suspend=Y
