SectionVerb {
	Value {
		FullySpecifiedUCM "1"
	}

	EnableSequence [
		cdev "hw:sc7180adau7002max"
	]

	DisableSequence [
	]
}

SectionDevice."Speaker".0 {
	Value {
		PlaybackPCM "hw:sc7180adau7002max,1"
		DspName "speaker_eq"
	}
	EnableSequence [
	]
	DisableSequence [
	]
}

SectionDevice."Internal Mic".0 {
	Value {
		CapturePCM "hw:sc7180adau7002max,0"
		CaptureChannelMap "0 1 -1 -1 -1 -1 -1 -1 -1 -1 -1"
		IntrinsicSensitivity "-2840"
	}
	EnableSequence [
	]
	DisableSequence [
	]
}

SectionDevice."HDMI".0 {
	Value {
		PlaybackPCM "hw:sc7180adau7002max,2"
		JackDev "sc7180-snd-card HDMI Jack"
	}

	EnableSequence [
	]
	DisableSequence [
	]
}
