# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

description     "Set multi-gen LRU min_ttl_ms to mitigate memory thrashing"
author          "fshao@chromium.org"

start on started boot-services
task
oom score -100

script
    echo 100 > /sys/kernel/mm/lru_gen/min_ttl_ms
end script
