# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

description   "Enable FW WP on Drawlat/drawman rev1 to avoid firmware incompatibilities."
author        "chromiumos-dev@chromium.org"

start on started system-services
task
oom score -100   # Short task at startup; don't oom kill

script
  set -e

  logit() {
    logger -t "${UPSTART_JOB}" "$@"
  }

  # Trigger only on drawlat or drawman.
  # Drawcia already has mature silicon.
  model="$(cros_config / name)"
  if [ "${model}" != "drawlat" -a "${model}" != "drawman" ] ; then
    logit "Leaving WP alone for ${model}"
    exit 0
  fi

  # Trigger only for rev1.
  rev="$(ectool cbi get 0 | grep 'As binary: ' | sed 's/As binary: //')"
  if [ "${rev}" -ne 1 ]; then
    logit "Leaving WP alone for ${model} rev${rev}"
    exit 0
  fi

  # Only blow WP if the RO FW is up to date.
  fwid="$(crossystem ro_fwid)"
  fwnum="$(echo ${fwid} | sed -n 's/Google_Drawcia\.\([0-9]*\)\..*/\1/p')"
  if [ "${fwnum}" -lt 13606 ]; then
    logit "Not enabling WP for old FW ${fwnum}"
    exit 0
  fi

  if crossystem cros_debug?1 ; then
    logit "Not write-protecting debug image."
    exit 0
  fi

  if ! crossystem mainfw_type?normal ; then
    logit "Not write-protecting devmode image"
    exit 0
  fi

  logit "Enabling WP for ${model} rev${rev} ${fwnum}"
  cros_wp -t host enable
end script
